#!/usr/bin/env python

# Mandatory variables
top = '.'
out = 'build'

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    obj = bld(features = 'cxx cxxprogram')
    obj.includes = [ '.' ]
    obj.source = [ 'main.cpp', 'systemtest.cpp' ]
    obj.target = 'sanityCheck'
    obj.name = 'sanityCheck'
    obj.install_path = bld.env['LIBDIR']
